version: '3.9'

volumes:
  root_pipelinelab:
  pipelinelab_db_data:

services:
  proxy:
    image: nginx
    container_name: pipelinelab_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  api_pipelinelab:
    image: webdevops/php-nginx:8.2-alpine
    container_name: api_pipelinelab
    working_dir: /app
    restart: on-failure
    expose:
      - "80"
    ports:
      - "9000:80"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 5g
    volumes:
      - .:/app:delegated
      - root_pipelinelab:/root
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
  mysql:
    platform: linux/x86_64
    image: mysql:8
    container_name: pipelinelab_db
    restart: on-failure
    working_dir: /app
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'pipelinelab'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret123'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - ./data:/app:rw
      - pipelinelab_db_data:/var/lib/mysql
